### ISSUE TITLE
Add function to download settings

### ISSUE THREAD

**Issue by svx** [ocular-d/writing-extension-pack#10]
Think about a way to start configuration out of VS-Code.

Like a script or own extra addon

**Comment by svx** [comment]
Use a public gist for settings:
https://dev.to/shanalikhan/how-to-share-your-visual-studio-code-settings-and-extensions-39k

To solve:
- Nice way to install dependencies

**Comment by svx** [comment]
Should we try `npx` for npm related stuff and also a custom `package.json` which ppl could *dump* ?

For vale check homebrew and a bash script which also should be smart enough to check for updates

**Comment by svx** [comment]
https://shanalikhan.github.io/2016/09/02/how-to-Share-visual-studio-code-settings.html

**Comment by svx** [comment]
https://mikefrobbins.com/2019/03/21/backup-and-synchronize-vscode-settings-with-a-github-gist/#comment-39448

**Comment by ocular-d** [comment]
Add to docs that user can download *just* the extension pack and can configure on the own, or their can download the pack and configure to use the public sync.

**Attention: Be careful with the settings we place, like we do not want to add our own GitHub settings**

**Comment by ocular-d** [comment]
First public *sync*: https://gist.github.com/ocular-d/ac10d2bd9cce717e8fcbbfff7852282b

**Comment by ocular-d** [comment]
Quick and dirty example for setting up vale on linux, this one also has a build in check for doing updates.

**Attention, this is a quick and dirty example, do not use it in production!**

```shell
#!/bin/bash

# Vars
BIN_DIR=$HOME/bin
CUR_VERSION="$("$BIN_DIR"/vale -v 2>/dev/null | awk '{print $NF;}')"
NEW_VERSION="$(curl -s https://api.github.com/repos/errata-ai/vale/releases/latest | sed -n 's/.*tag_name":\s"\(.*\)".*/\1/p' | head -1)"
DOW_VERSION="$(curl -s https://api.github.com/repos/errata-ai/vale/releases/latest | sed -n 's/.*tag_name":\s"\(.*\)".*/\1/p' | head -1 | cut -c 2-)"

echo "Vale:  Current Version: $CUR_VERSION => New Version: $DOW_VERSION"

if [ "$CUR_VERSION" != "$DOW_VERSION" ]; then
  echo "get new version"
  curl -L --output vale.tar.gz "https://github.com/errata-ai/vale/releases/download/${NEW_VERSION}/vale_${DOW_VERSION}_Linux_64-bit.tar.gz"
  tar -C "${BIN_DIR}" -xvzf vale.tar.gz vale
  rm vale.tar.gz
else
    echo "Vale is up to date"
fi
```

**Comment by ocular-d** [comment]
settings sync is added to the package.json but still missing in the README
