### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by ocular-d** [ocular-d/writing-extension-pack#4]
Add docs about:

- Publishing a new version
- Configure add-ons (link to gist)
- Install dependencies 
- Add and test new add-on

**Comment by ocular-d** [comment]
Add a `package.json` which will install all dependencies in the project dir, add to gist and makefile and bot for dependency update check

**Comment by svx** [comment]
Add screens of settings. themes and of an working example setup, maybe "frame" them with a "macOS" look and feel?

**Comment by svx** [comment]
Create docker container with gatsby which we can use for building the docs.
By doing so we can keep `/docs` clean and would only have the `.md` files there.

Later add a GitHub action for building the docs :)

**Comment by svx** [comment]
We do not need gatsby since we'll use vue

**Comment by svx** [comment]
Old version 2.0 will be different
